import Footer from '../../components/ui/footer'
import Navbar from '../../components/ui/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hackathon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'${inter.className} bg-myWhite'}>
        <div className='max-w-[90%] mx-auto'>
         
          <Providers>

         <Navbar />
        
        {children}
        <Footer />
        </Providers>
        </div>
        </body>
    </html>
  )
}
