import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    title: "Black Men Top",
    image: ["/event2.webp"],
    slug: "black-men-top",
    price: 200,
    category: "tops",
    description: "Best quality top for men.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 2,
    title: "Black Women Top",
    image: ["/p1.png"],
    slug: " women-top",
    price: 200,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 3,
    title: "Women Top",
    image: ["/p3.png"],
    slug: "women-top-black",
    price: 200,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 4,
    title: "Women Trouser",
    image: ["/p4.png"],
    slug: "trouser-women-12",
    price: 200,
    category: "trousers",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 5,
    title: "Women Trouser",
    image: ["/p5.png"],
    slug: "trouser-123",
    price: 200,
    category: "trousers",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60500"],
    qty: 1,
    discount: 0,
  },
  {
    id: 6,
    title: "Women Trouser",
    image: ["/p6.png"],
    slug: "trouser-345",
    price: 200,
    category: "trousers",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 7,
    title: "Women Top",
    image: ["/p7.png"],
    slug: "top-hoody",
    price: 200,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 8,
    title: "Men Top",
    image: ["/p8.png"],
    slug: "top-for-men",
    price: 250,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 9,
    title: "Women Sleeveless Top",
    image: ["/p9.png"],
    slug: "sleevless-top",
    price: 200,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 10,
  },
  {
    id: 10,
    title: "Women Top",
    image: ["/p10.png"],
    slug: "top-6",
    price: 200,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 11,
    title: "Women Top",
    image: ["/p11.png"],
    slug: "trousers-women-new",
    price: 200,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 12,
    title: "Pendant",
    image: ["/jewelry1.jpg"],
    slug: "jewelry",
    price: 200,
    category: "jewelry",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 13,
    title: "Pendant",
    image: ["/pend3.jpg"],
    slug: "jewelry-1",
    price: 200,
    category: "jewelry",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 14,
    title: "Women Top",
    image: ["/pendant2.jpg"],
    slug: "jewelry-2",
    price: 200,
    category: "jewelry",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 15,
    title: "Heels",
    image: ["/shoes.jpg"],
    slug: "shoes-1",
    price: 200,
    category: "shoes",
    description: "Blue Printed Heels for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 16,
    title: "White Heels",
    image: ["/shoes2.jpg"],
    slug: "shoe-2",
    price: 200,
    category: "shoes",
    description: "White trendy Heels for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 17,
    title: "Elegant Jewelry",
    image: ["/jewelry.jpg"],
    slug: "jewelry-new-collection",
    price: 200,
    category: "jewelry",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
  {
    id: 18,
    title: "Women Dress",
    image: ["/header.webp"],
    slug: "dress-for-women",
    price: 540,
    category: "tops",
    description: "Best quality top for women.",
    size: ["S", "M", "L", "XL"],
    colour: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 0,
  },
];
